


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: number
        category:
          type: string
        status:
          type: boolean
        code:
          type: string
        thumbnails:
          type: array
      example:
        title: "Arroz"
        description: "Arroz fino premium"
        price: 10.99
        stock: 100
        category: "Alimentos"
        status: true
        code: "AARRPREMIUM"
        thumbnails:
          - "https://example.com/thumbnail1.jpg"
          - "https://example.com/thumbnail2.jpg"

paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Get all products
      description: Get all products
      operationId: getProducts
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
      security:
        - bearerAuth: []  # Aquí se aplica la seguridad
    post:
      tags:
        - Products
      summary: Create a new product
      description: Create a new product
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: "Producto ya creado con llave duplicada"
        500:
          description: "Error en crear proyecto"
      security:
        - bearerAuth: []  # Aquí se aplica la seguridad

  /api/products/{id}:
    get:
      tags:
        - Products
      summary: Get product by id
      description: Get product by id
      operationId: getProductById
      parameters:
        - name: id
          in: path
          description: ID of the product
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: "Producto no encontrado"
        500:
          description: "Error en crear proyecto"
      security:
        - bearerAuth: []  # Aquí se aplica la seguridad
    
    put:
      tags:
        - Products
      summary: Update a product
      description: Update a product
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          description: ID of the product
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: "Producto no encontrado"
        500:
          description: "Error en crear proyecto"
      security:
        - bearerAuth: []  # Aquí se aplica la seguridad

    delete:
      tags:
        - Products
      summary: Delete a product
      description: Delete a product
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          description: ID of the product
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: "Producto no encontrado"
        500:
          description: "Error en crear proyecto"
      security:
        - bearerAuth: []  # Aquí se aplica la seguridad
  